name: astro
channels:
  - defaults
dependencies:
  - matplotlib
  - jupyter
  - scikit-learn
  - autograd
  - astropy
  - emcee
  - wheel
  - pyflakes
  - pip
  - astroid
  - scipy
  - cython
  - uncertainties
  - sphinx
  - george
  - jupyterlab
  - jedi
  - seaborn
  - nbsphinx
  - numpy
  - h5py
  - corner
  - pandas
  - sympy
  - pylint
  - conda-build
  - celerite
  - ipython
  - cryptography
  - flake8
  - pynvim
  - pip:
    - -r requirements.txt
